---
- name: install single k8s node
  hosts: k8s-0001
  roles:
    - role: base
      tags: base
    - role: zfs
      tags: zfs
    - role: cri-o
      tags: cri-o
    - role: kubeadm
      tags: kubeadm
    - role: calico
      tags: calico
    - role: openebs
      tags: openebs
    - role: cert-manager
      tags: cert-manager
    - role: ingress-nginx
      tags: ingress-nginx
    - role: metallb
      tags: metallb
    - role: kubevirt
      tags: kubevirt
