---
- name: check input
  assert:
    that:
    - k8s_version is defined
    - k8s_subnet_cidr is defined
    - k8s_dns_domain is defined

- name: packages
  apt:
    name:
    - ebtables
    - socat
    - conntrack

- name: install kubeadm, kubelet, kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/{{ item }}
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  loop:
  - kubeadm
  - kubelet
  - kubectl

- name: /etc/systemd/system/kubelet.service
  copy:
    src: kubelet.service
    dest: /etc/systemd/system/kubelet.service

- name: /etc/systemd/system/kubelet.service.d
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory

- name: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  copy:
    src: 10-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  
- name: kubelet service
  service:
    name: kubelet
    enabled: yes
    state: started

- name: kubeadm config file
  template:
    src: kubeadm-config.yaml.j2
    dest: /root/kubeadm-config.yaml
    owner: root
    group: root
    mode: 0644

- name: kubeadm init
  command: kubeadm init --config=/root/kubeadm-config.yaml
  args:
    creates: /etc/kubernetes/admin.conf

- name: wait for api-server to be available
  wait_for:
    port: 6443

- name: /root/.kube
  file:
    path: /root/.kube
    owner: root
    group: root
    mode: 0700
    state: directory

- name: kubectl config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: 0600
    remote_src: True

- name: remove master node taint
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  failed_when: False
