---
- name: check input
  assert:
    that:
      - kubevirt_version is defined
  tags:
    - check_input

- name: install kubevirt
  command: kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/{{ kubevirt_version }}/{{ item }}
  loop:
    - kubevirt-operator.yaml
    - kubevirt-cr.yaml

- name: virtctl
  get_url:
    url: https://github.com/kubevirt/kubevirt/releases/download/{{ kubevirt_version }}/virtctl-{{ kubevirt_version }}-linux-amd64
    dest: /usr/local/bin/virtctl
    owner: root
    group: root
    mode: 0755
