---
- name: check input
  assert:
    that:
      - secret is defined
      - secret is mapping
      - secret.name is defined
      - secret.key is defined
      - secret.file is defined
  tags:
    - check_input

- name: stat secret file
  stat:
    path: "{{ secret.file }}"
  register: secret_file
  tags:
    - check_input

- name: fail if secret file does not exist
  fail:
    msg: "{{ secret.file }} does not exist"
  when: not secret_file.stat.exists
  tags:
    - check_input

- name: create secret
  command: kubectl -n cert-manager create secret generic {{ secret.name }} --from-file={{ secret.key }}={{ secret.file }}
  register: create_secret
  failed_when: create_secret.rc > 0 and "already exists" not in create_secret.stderr
  changed_when: |
    "already exists" not in create_secret.stderr
